const books = [{
    "id": 1,
    "Bookname": "Dennie",
    "price": 858,
    "autherName": "Francisca",
    "publisherName": "Salvatore",
    "publisherDate": "5/15/2021",
    "edition": 2017
  }, {
    "id": 2,
    "Bookname": "Gale",
    "price": 580,
    "autherName": "Petunia",
    "publisherName": "Erroll",
    "publisherDate": "9/24/2021",
    "edition": 2009
  }, {
    "id": 3,
    "Bookname": "Gabrielle",
    "price": 541,
    "autherName": "Alexei",
    "publisherName": "Albie",
    "publisherDate": "7/26/2021",
    "edition": 1999
  }, {
    "id": 4,
    "Bookname": "Kristin",
    "price": 351,
    "autherName": "Max",
    "publisherName": "Wernher",
    "publisherDate": "3/29/2022",
    "edition": 2012
  }, {
    "id": 5,
    "Bookname": "Cullan",
    "price": 559,
    "autherName": "Craggie",
    "publisherName": "Dinah",
    "publisherDate": "6/25/2021",
    "edition": 2009
  }, {
    "id": 6,
    "Bookname": "Efren",
    "price": 582,
    "autherName": "Hilda",
    "publisherName": "Ikey",
    "publisherDate": "12/20/2021",
    "edition": 2005
  }, {
    "id": 7,
    "Bookname": "Tallou",
    "price": 553,
    "autherName": "Jackquelin",
    "publisherName": "Stafani",
    "publisherDate": "6/14/2021",
    "edition": 2001
  }, {
    "id": 8,
    "Bookname": "Teador",
    "price": 137,
    "autherName": "Stephen",
    "publisherName": "Gennifer",
    "publisherDate": "8/24/2021",
    "edition": 2014
  }, {
    "id": 9,
    "Bookname": "Chet",
    "price": 182,
    "autherName": "Lemmie",
    "publisherName": "Nadeen",
    "publisherDate": "11/5/2021",
    "edition": 2014
  }, {
    "id": 10,
    "Bookname": "Fanni",
    "price": 797,
    "autherName": "Amelie",
    "publisherName": "Yasmin",
    "publisherDate": "10/24/2021",
    "edition": 2019
  }, {
    "id": 11,
    "Bookname": "Othilie",
    "price": 72,
    "autherName": "Enrique",
    "publisherName": "Jessalin",
    "publisherDate": "12/12/2021",
    "edition": 2020
  }, {
    "id": 12,
    "Bookname": "Aretha",
    "price": 212,
    "autherName": "Lucille",
    "publisherName": "Charita",
    "publisherDate": "7/26/2021",
    "edition": 2018
  }, {
    "id": 13,
    "Bookname": "Amory",
    "price": 455,
    "autherName": "Bordy",
    "publisherName": "Adriena",
    "publisherDate": "6/25/2021",
    "edition": 2019
  }, {
    "id": 14,
    "Bookname": "Moises",
    "price": 886,
    "autherName": "Letti",
    "publisherName": "Brant",
    "publisherDate": "9/4/2021",
    "edition": 2003
  }, {
    "id": 15,
    "Bookname": "Catarina",
    "price": 86,
    "autherName": "Juanita",
    "publisherName": "Mohandis",
    "publisherDate": "8/22/2021",
    "edition": 2013
  }, {
    "id": 16,
    "Bookname": "Obediah",
    "price": 906,
    "autherName": "Scotty",
    "publisherName": "Rozamond",
    "publisherDate": "1/21/2022",
    "edition": 1999
  }, {
    "id": 17,
    "Bookname": "Caria",
    "price": 577,
    "autherName": "Calhoun",
    "publisherName": "Harli",
    "publisherDate": "11/10/2021",
    "edition": 2020
  }, {
    "id": 18,
    "Bookname": "Kacy",
    "price": 438,
    "autherName": "Alli",
    "publisherName": "Cahra",
    "publisherDate": "1/15/2022",
    "edition": 1999
  }, {
    "id": 19,
    "Bookname": "Othello",
    "price": 400,
    "autherName": "Blondelle",
    "publisherName": "Devonne",
    "publisherDate": "1/13/2022",
    "edition": 2021
  }, {
    "id": 20,
    "Bookname": "Denyse",
    "price": 798,
    "autherName": "Willy",
    "publisherName": "Caralie",
    "publisherDate": "7/27/2021",
    "edition": 2015
  }];

  module.exports = books;